# Generated by Django 6.0.2 on 2026-02-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='career',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_music',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passions',
            field=models.TextField(blank=True),
        ),
    ]
