# Generated by Django 6.0.2 on 2026-02-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_career_user_education_user_favorite_music_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='interested_in',
            field=models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman'), ('everyone', 'Everyone')], max_length=10),
        ),
    ]
